"""empty message

Revision ID: 487ed3c27d4d
Revises: 89eec570bc1d
Create Date: 2023-12-03 17:16:42.485660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487ed3c27d4d'
down_revision = '89eec570bc1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    op.drop_table('cohorts')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('students_cohort_id_fkey', type_='foreignkey')
        batch_op.drop_column('cohort_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cohort_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('students_cohort_id_fkey', 'cohorts', ['cohort_id'], ['id'])

    op.create_table('cohorts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name='cohorts_admin_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cohorts_pkey')
    )
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('_password_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='admins_pkey')
    )
    # ### end Alembic commands ###
