"""added some more rules

Revision ID: 768b48d369a6
Revises: 4b4af5569ff5
Create Date: 2023-12-22 01:48:29.773642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '768b48d369a6'
down_revision = '4b4af5569ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('StudentsProjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'request', ['request_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('StudentsProjects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('request_id')

    # ### end Alembic commands ###
